---
- name: resource_manager modules examples
  hosts: localhost
  gather_facts: false
  tasks:
    - name: List ibm_resource_group
      ibm_resource_group_info:
        id: 'Default'
      register: get_resource_group_result
    - name: Print list result
      debug:
        var: get_resource_group_result
